# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 69e8d99d8ab9f5e75b76cc0ac6c773a82aea81fbc7ce83cf60776b6942cb3aa4f90e7d201936c67b5a3cacaef394754dd51560d6b138e7407874d96cfc226556

test:
  secret_key_base: 2641f3304181c9de0d2194cbf1ec5629a91dd51f5edea819d77117336dcfa42d9453850eeefcf9696c7f33bd79298ffecd03a1f36dfbff13e0df9675e1388d49

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
